language: ruby
rvm:
  - "2.0.0"
# uncomment this line if your project needs to run something other than `rake`:
script: bundle exec rspec spec
before_script:
  - psql -c 'create database soundscript_test;' -U postgres