# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 261efb632f4981e05d5f77ccb247ff0c01533391d6528909315a2d3476ae2f6756a0492bdbcc57dbb962b15b873601bf5acbda1cd6e2f37aa11ece5eb71f938c

test:
  secret_key_base: 2d8130bfd2c17bbb2415f844578f0e0c0a791450bef573cfaa6a1492a5209946f864dff9c6117b922bb4c5fbc6e5d3c32c9fdbd5a5a3bbaa0c7736a7df971e7e

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
