User.create(username:"monica", password: "password", email: 'monica@yahoo.com')
User.create(username:"milan", password: "1111", email: "milan@dbc.com")

languages = ["English","Spanish","Chinese (Cantonese)", "Chinese (Mandarin)","Tagalog", "French","Vietnamese", "German", "Korean", "Italian","Russian", "Korean","Arabic", "Italian", "Portuguese","French Creole","Polish", "Japanese", "Serbian (Cyrillic)", "Serbian (Latin)", "Other"]


languages.each do |lang|
	Language.create(title: lang)
end


Track.create(user_id: 2, youtube_id: "b0NHrFNZWh0", language_id: 18, transcript: "{\"0\":{\"content\":\"Пет мали мајмуни скакање на кревет.\",\"position_css\":\"top: 72px; left: 2225px; width: 560px; height: 50px;\"},\"1\":{\"content\":\"Један је пао и ударио главом.\",\"position_css\":\"top: 2px; left: 2691px;\"},\"2\":{\"content\":\"Дакле, мама зове доктора и доктор рекао.\",\"position_css\":\"top: 102px; left: 3379px;\"},\"3\":{\"content\":\"Nomo majmune skakati na krevet!\",\"position_css\":\"top: 51px; left: 4041px;\"},\"4\":{\"content\":\"четири мале мајмуни скакање на кревет.\",\"position_css\":\"top: 77px; left: 5347px;\"},\"5\":{\"content\":\"Један је пао и ударио главом.\",\"position_css\":\"top: 28px; left: 5923px;\"},\"6\":{\"content\":\"Дакле, мама зове доктора и доктор рекао.\",\"position_css\":\"top: 94px; left: 6619px;\"},\"7\":{\"content\":\"Дакле, мама зове доктора и доктор рекао.\",\"position_css\":\"top: 68px; left: 10439px;\"},\"8\":{\"content\":\"Дакле, мама зове доктора и доктор рекао.\",\"position_css\":\"top: 61px; left: 13560px;\"},\"9\":{\"content\":\"Дакле, мама зове доктора и доктор рекао.\",\"position_css\":\"top: 51px; left: 17525px;\"},\"10\":{\"content\":\"Дакле, мама зове доктора и доктор рекао.\",\"position_css\":\"top: 69px; left: 20688px;\"},\"11\":{\"content\":\"Стави те мајмуне назад у кревет!\",\"position_css\":\"top: 2px; left: 21221px;\"},\"12\":{\"content\":\"Нема више мајмуни скакање по кревету!\",\"position_css\":\"top: 2px; left: 7186px;\"},\"13\":{\"content\":\"Један је пао и ударио главом. \",\"position_css\":\"top: 51px; left: 9794px;\"},\"14\":{\"content\":\"Три мале мајмуни скакање на кревет.\",\"position_css\":\"top: 127px; left: 9353px;\"},\"15\":{\"content\":\"Нема више мајмуни скакање по кревету! \",\"position_css\":\"top: 125px; left: 11052px;\"},\"16\":{\"content\":\"Један је пао и ударио главом. \",\"position_css\":\"top: 2px; left: 12927px;\"},\"17\":{\"content\":\"Две мале мајмуни скакање на кревет.\",\"position_css\":\"top: 102px; left: 12404px;\"},\"18\":{\"content\":\"Нема више мајмуни скакање по кревету! \",\"position_css\":\"top: 102px; left: 14167px;\"},\"19\":{\"content\":\"Један мали мајмуни скакање на кревет.\",\"position_css\":\"top: 51px; left: 16198px;\"},\"20\":{\"content\":\"Он је пао и ударио главом.\",\"position_css\":\"top: 130px; left: 16773px;\"},\"21\":{\"content\":\"Нема више мајмуни скакање по кревету!\",\"position_css\":\"top: 102px; left: 18114px;\"},\"22\":{\"content\":\"Нема мале мајмуни скакање на кревет.\",\"position_css\":\"top: 51px; left: 19438px;\"},\"23\":{\"content\":\"Ниједан пао и ударио главом.\",\"position_css\":\"top: 102px; left: 19950px;\"}}"
)

Track.create(user_id: 2, youtube_id: "b0NHrFNZWh0", language_id: 1, transcript: "{\"0\":{\"content\":\"Five little monkeys jumping on the bed.\",\"position_css\":\"top: 51px; left: 2158px;\"},\"1\":{\"content\":\"One fell off and bumped his head.\",\"position_css\":\"top: 102px; left: 2714px;\"},\"2\":{\"content\":\"So mama called the doctor and the doctor said.\",\"position_css\":\"top: 100px; left: 3400px; height: 46px; width: 671px;\"},\"3\":{\"content\":\"No more monkeys jumping on the bed!\",\"position_css\":\"top: 51px; left: 4048px;\"},\"4\":{\"content\":\"Four little monkeys jumping on the bed.\",\"position_css\":\"top: 51px; left: 5341px;\"},\"5\":{\"content\":\"One fell off and bumped his head.\",\"position_css\":\"top: 102px; left: 5902px;\"},\"6\":{\"content\":\"So momma called the doctor and the doctor said.\",\"position_css\":\"top: 35px; left: 6619px; height: 111px;\"},\"7\":{\"content\":\"No more monkeys jumping on the bed!\",\"position_css\":\"top: 151px; left: 7236px;\"},\"8\":{\"content\":\"Three little monkeys jumping on a bed.\",\"position_css\":\"top: 51px; left: 9190px;\"},\"9\":{\"content\":\"One fell off and bumped his head.\",\"position_css\":\"top: 102px; left: 9825px;\"},\"10\":{\"content\":\"So momma called the doctor and the doctor said.\",\"position_css\":\"top: 0px; left: 10435px; height: 90px;\"},\"11\":{\"content\":\"No more monkeys jumping on the bed!\",\"position_css\":\"top: 102px; left: 11060px;\"},\"12\":{\"content\":\"Two little monkeys jumping on the bed.\",\"position_css\":\"top: 102px; left: 12418px;\"},\"13\":{\"content\":\"One fell off and bumped his head.\",\"position_css\":\"top: 51px; left: 12956px;\"},\"14\":{\"content\":\"No more monkeys jumping on the bed!\",\"position_css\":\"top: 102px; left: 14232px;\"},\"15\":{\"content\":\"One little monkey jumping on the bed.\",\"position_css\":\"top: 51px; left: 16247px;\"},\"16\":{\"content\":\"He fell off and bumped his head.\",\"position_css\":\"top: 102px; left: 16781px;\"},\"17\":{\"content\":\"\",\"position_css\":\"top: 26px; left: 17651px; height: 44px; width: 661px;\"},\"18\":{\"content\":\"No more monkeys jumping on the bed!\",\"position_css\":\"top: 151px; left: 18153px;\"},\"19\":{\"content\":\"None fell off and bumped his head.\",\"position_css\":\"top: 102px; left: 19963px;\"},\"20\":{\"content\":\"So momma called the doctor and the doctor said.\",\"position_css\":\"top: 78px; left: 20682px; height: 105px;\"},\"21\":{\"content\":\"Put those monkeys back in the bed!\",\"position_css\":\"top: 2px; left: 21211px;\"},\"22\":{\"content\":\"So momma called the doctor and the doctor said!\",\"position_css\":\"top: 98px; left: 13557px; height: 89px;\"},\"23\":{\"content\":\"So momma called the doctor and the doctor said.\",\"position_css\":\"top: 105px; left: 17550px;\"},\"24\":{\"content\":\"No little monkeys jumping on the bed.\",\"position_css\":\"top: 71px; left: 19370px;\"}}"
)


